services:
  traefik:
    image: traefik:3.0.0
    container_name: traefik
    init: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-public
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=America/Santiago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic.yml:/dynamic.yml:ro
      - ./users.txt:/users.txt:ro
      - ./acme.json:/acme.json
      - logs:/var/log/traefik
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik.loadbalancer.server.port=80
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.rule=Host(`${DNS}`)
      - traefik.http.routers.traefik-secure.middlewares=myauth@file
      - traefik.http.routers.traefik-secure.service=api@internal

volumes:
  logs: {}

networks:
  traefik-public:
    external: true
